[WIP] TW-1455: Fix micro permission when opening camera in chat
linagora/twake-on-matrix pull request #1491
Opened 2024-02-21 10:41 UTC by nqhhdev

### Ticket

- #1455

### Resolved:

2024-02-22 10:51 UTC, Te-Z requested changes

2024-02-22 10:51 UTC, Te-Z commented on lib/utils/permission_service.dart
> +      return newStatus.isGranted ? PermissionStatus.granted : newStatus;
I think you can directly do this here:
`return Permission.microphone.request()`

2024-02-23 08:05 UTC, Te-Z approved these changes

2024-02-23 08:44 UTC, hoangdat commented on ios/Podfile
> +  ##end
please careful on it

2024-02-26 03:15 UTC, sherlockvn commented on lib/presentation/mixins/media_picker_mixin.dart
> +    if (currentPermissionMicro == PermissionStatus.granted &&
can you handle the case when microphone is not granted, but camera is granted

2024-02-26 05:04 UTC, hoangdat approved these changes

2024-02-26 05:04 UTC, merged