fix: dismiss keyboard on scroll in new grp view
linagora/twake-on-matrix pull request #377
Opened 2023-07-27 16:54 UTC by imGok

![demo_scroll](https://github.com/linagora/twake-on-matrix/assets/48354990/8b73261e-9003-4d0e-a995-22e207483e02)

This Closes #250

2023-07-28 03:07 UTC, dab246 approved these changes
lgtm

2023-07-28 07:23 UTC, drminh2807 requested changes

2023-07-28 07:23 UTC, drminh2807 commented on lib/pages/dialer/pip/dismiss_keyboard.dart
> +  final FocusScopeNode currentFocus = FocusScope.of(context);
```suggestion
  FocusManager.instance.primaryFocus?.unfocus();
```
No need context anymore

2023-07-28 08:50 UTC, imGok commented on lib/pages/dialer/pip/dismiss_keyboard.dart
> +  final FocusScopeNode currentFocus = FocusScope.of(context);
thank u, I modified it

2023-07-29 09:24 UTC, hoangdat commented on lib/pages/new_group/selected_contacts_map_change_notiifer.dart
> +  void onContactTileTap({required PresentationContact contact, required BuildContext context}) {
all are `required`, why need `{ }`? I will take time of the dev :))). a small point.

2023-07-31 05:10 UTC, drminh2807 approved these changes

2023-07-31 05:11 UTC, hoangdat approved these changes

2023-07-31 09:18 UTC, hoangdat approved these changes

2023-07-31 09:18 UTC, merged